name: Run Python Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.8, 3.9]

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
      # Checkout the repository code

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
      # Set up Python environment

    - name: Cache Python packages
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
      # Cache Python dependencies to speed up workflow

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
      # Install dependencies

    - name: Run tests
      run: |
        python -m pytest
      # Run tests, assuming pytest is discovering tests automatically
